export const LABELS = {
  APP: {
    TITLE: 'PI Planning Tool',
    THEME_DARK: '🌙 Dark',
    THEME_LIGHT: '☀️ Light',
    GUEST: 'Guest',
  },
  BUTTONS: {
    CANCEL: 'Cancel',
    CLOSE: 'Close',
    SAVE: 'Save',
    SAVE_CAPACITY: 'Save Capacity',
    DELETE: 'Delete',
    RETRY: 'Retry',
    GO_TO_BOARDS: 'Go to Boards List',
    VALIDATE_OPEN: 'Validate & Open Board',
    VALIDATING: 'Validating...',
    IMPORT_FEATURE: 'Import Feature',
    IMPORTING: 'Importing...',
    REFRESH_FEATURE: 'Refresh Feature',
    REFRESH_FROM_AZURE: 'Refresh from Azure',
    REFRESHING: 'Refreshing...',
    DELETE_FEATURE: 'Delete Feature',
    DELETING: 'Deleting...',
    CREATE_BOARD: 'Create Board',
    CREATING: 'Creating...',
    CREATE_NEW: '+ Create New',
    BACK_HOME: '← Back to Home',
    BACK: '← Back',
    ADD_MEMBER: '+ Add Member',
    ADD_MEMBER_PLAIN: 'Add Member',
    UPDATE_MEMBER: 'Update Member',
    ADD_FEATURE: '+ Add Feature',
    FINALIZE: '✓ Finalize',
    FINALIZE_CONFIRM: 'Yes, Finalize Board',
    FINALIZING: 'Finalizing...',
    RESTORE: '↺ Restore',
    RESTORE_PLAIN: 'Restore',
    RESTORING: '⟳ Restoring...',
    START_BOARD: 'Start Board',
    EDIT: 'Edit',
    OPEN: 'Open →',
  },
  HEADERS: {
    BOARD_LIST: 'Your Boards',
    CREATE_BOARD: 'Create New Board',
    IMPORT_FEATURE: 'Import Feature from Azure DevOps',
    REFRESH_FEATURE: 'Refresh Feature from Azure DevOps',
    DELETE_FEATURE: 'Delete Feature',
    FINALIZE_BOARD: 'Finalize Board',
    TEAM_MEMBERS: 'Team Members',
    ADD_TEAM_MEMBER: 'Add Team Member',
    EDIT_TEAM_MEMBER: 'Edit Team Member',
    DELETE_TEAM_MEMBER: 'Delete Team Member',
    EDIT_TEAM_CAPACITY: 'Edit Team Capacity',
    PAT_REQUIRED: 'Azure DevOps PAT Required',
  },
  FIELDS: {
    FEATURE_ID: 'Feature ID (User Story ID) *',
    FEATURE: 'Feature',
    AZURE_ID: 'Azure ID',
    AZURE_STORY_POINT_FIELD: 'Azure Story Point Field',
    AZURE_DEV_STORY_POINT_FIELD: 'Azure Dev Story Point Field',
    AZURE_TEST_STORY_POINT_FIELD: 'Azure Test Story Point Field',
    ORGANIZATION: 'Organization',
    ORGANIZATION_REQUIRED: 'Organization *',
    PROJECT: 'Project',
    PROJECT_REQUIRED: 'Project *',
    ORGANIZATION_NAME_REQUIRED: 'Organization Name (Required)',
    PROJECT_NAME_REQUIRED: 'Project Name (Required)',
    PAT: 'Personal Access Token (PAT) *',
    PAT_INPUT: 'Personal Access Token (PAT)',
    TEAM: 'Team',
    CAPACITY: 'Capacity',
    LOAD: 'Load',
    SPRINT: 'Sprint',
    BOARD_NAME: 'Board Name',
    NUM_SPRINTS: 'Number of Sprints',
    SPRINT_DURATION: 'Sprint Duration (days)',
    START_DATE: 'Start Date',
    DEV_TEST_TOGGLE: 'Dev/Test Toggle',
    DEV: 'Dev',
    TEST: 'Test',
    TOTAL: 'Total',
    PARKING_LOT: 'Parking Lot',
    MEMBER_NAME: 'Name',
    ROLE: 'Role',
    EDIT_MEMBER: 'Edit member',
  },
  FILTERS: {
    LOCKED_ONLY: 'Locked Only',
    FINALIZED_ONLY: 'Finalized Only',
  },
  INFO: {
    ORG: 'Org:',
    PROJECT: 'Project:',
    SPRINTS: 'Sprints:',
    FEATURES: 'Features:',
    CREATED: 'Created:',
  },
  OPERATIONS: {
    ADD_MEMBERS: 'add members',
    DELETE_MEMBERS: 'delete members',
    ADD_FEATURES: 'add features',
    EDIT_CAPACITY: 'edit capacity',
  },
  UNITS: {
    POINTS: 'pts',
  },
  OPTIONS: {
    DEV: 'Developer',
    TEST: 'Tester',
  },
  BADGES: {
    LOCKED: '🔒 Locked',
    FINALIZED: '✅ Finalized',
    FINALIZED_PLAIN: '✓ Finalized',
  },
  ROLES: {
    DEV: 'Dev',
    TEST: 'Test',
    DEV_TEST: 'Dev/Test',
    MEMBER: 'Member',
  },
  PAT: {
    remember: (minutes: number) => `Remember PAT for ${minutes} minutes`,
  },
  FINALIZE: {
    RESTRICTION_FEATURES: '❌ Add new features',
    RESTRICTION_MEMBERS: '❌ Add new team members',
    RESTRICTION_STORIES: '❌ Add new user stories (except via refresh to Sprint 0)',
  },
};
