export const PLACEHOLDERS = {
  PAT: 'Enter your Azure DevOps PAT',
  FEATURE_ID: 'e.g., 12345',
  AUTO_POPULATED: 'Auto-populated from board',
  ORG_EXAMPLE: 'e.g., Acme Corp',
  PROJECT_EXAMPLE: 'e.g., Platform',
  ORG_REQUIRED: 'e.g., MyOrganization',
  PROJECT_REQUIRED: 'e.g., MyProject',
  SEARCH_BOARDS: 'Search boards...',
  MEMBER_NAME: 'Enter member name',
  USER_NAME: 'Enter your name',
  BOARD_NAME: 'e.g., Q1 2026 Planning',
  STORY_POINT_FIELD: 'Microsoft.VSTS.Scheduling.StoryPoints',
  DEV_POINT_FIELD: 'Custom.DevStoryPoints',
  TEST_POINT_FIELD: 'Custom.TestStoryPoints',
  DEV: 'Dev',
  TEST: 'Test',
  CAPACITY: 'Capacity',
};
