services:
  db:
    build: ./db
    container_name: pi-postgres
    environment:
      POSTGRES_PASSWORD: "YourStrong!Passw0rd"
      POSTGRES_DB: PIPlanningDB
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/pg-data:/var/lib/postgresql/data
    restart: always
    networks:
      - pi-net

  backend:
    build: ./backend/pi-planning-backend
    container_name: pi-backend
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Host=pi-postgres;Database=PIPlanningDB;Username=postgres;Password=YourStrong!Passw0rd"
    ports:
      - "8080:8080"
    restart: always
    networks:
      - pi-net

  frontend:
    build: ./frontend/pi-planning-ui
    container_name: pi-frontend
    depends_on:
      - backend
    ports:
      - "4200:80"
    restart: always
    networks:
      - pi-net

networks:
  pi-net:
    driver: bridge
